version: '3.4'

services:
  seq:
    image: datalust/seq:latest

  rabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

  mint.webapp:
    image: ${DOCKER_REGISTRY-}mintwebapp
    build:
      context: .
      dockerfile: src/Mint.WebApp/Dockerfile
    ports:
      - 44411
    depends_on:
      - rabbitmq
