export const GET_PRODUCTS_FROM_CART = "GET_PRODUCTS_FROM_CART";

export const TOGGLE_CART = "TOGGLE_CART";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
