export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_ALL_MANUFACTURES = "GET_ALL_MANUFACTURES";
export const GET_ALL_SUBCATEGORIES = "GET_ALL_SUBCATEGORIES";
export const MENU = "MENU";
