export const CHANGE_LAYOUT_MODE = "CHANGE_LAYOUT_MODE";
export const CHANGE_LAYOUT_TYPE = "CHANGE_LAYOUT_TYPE";
export const CHANGE_LAYOUT_TYPE_SIZE = "CHANGE_LAYOUT_TYPE_SIZE";
export const CHANGE_LAYOUT_TYPE_MODE = "CHANGE_LAYOUT_TYPE_MODE";